version: '3'

services:
    blog:
        build: .
        container_name: blog
        ports:
            - "80:80"
        volumes:    
            - ./conf.d/site.conf:/etc/nginx/conf.d/default.conf          
        networks:
            - code-network

networks:
    code-network:
        driver: bridge